spring:
  datasource:
    password: ''
    url: jdbc:mysql://localhost:3306/bank_system?createDatabaseIfNotExist=true
    username: root
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create
    show-sql: true